Repository directus/app-next, pull requests merged in 2020-03, with the labels that each got.

#142 Add header bar to private view
  .storybook/decorators/with-alt-colors.ts
  .storybook/decorators/with-background.ts
  .storybook/decorators/with-padding.ts
  public/index.html
  src/components/register.ts
  src/components/v-breadcrumb/v-breadcrumb.vue
  src/components/v-button/v-button.readme.md
  src/components/v-button/v-button.vue
  src/components/v-icon/custom-icons/box.vue
  src/components/v-icon/v-icon.vue
  src/hydrate.test.ts
  src/modules/collections/routes/collections-overview.test.ts
  src/modules/collections/routes/collections-overview.vue
  src/styles/_base.scss
  src/styles/themes/_default.scss
  src/utils/parse-css-var.test.ts
  src/utils/parse-css-var.ts
  src/views/private-view/drawer-detail-group/drawer-detail-group.story.ts
  src/views/private-view/drawer-detail-group/drawer-detail-group.test.ts
  src/views/private-view/drawer-detail-group/drawer-detail-group.vue
  src/views/private-view/drawer-detail-group/index.ts
  src/views/private-view/drawer-detail-group/readme.md
  src/views/private-view/drawer-detail/drawer-detail.story.ts
  src/views/private-view/drawer-detail/drawer-detail.test.ts
  src/views/private-view/drawer-detail/drawer-detail.vue
  src/views/private-view/drawer-detail/index.ts
  src/views/private-view/drawer-detail/readme.md
  src/views/private-view/header-bar-actions/header-bar-actions.story.ts
  src/views/private-view/header-bar-actions/header-bar-actions.test.ts
  src/views/private-view/header-bar-actions/header-bar-actions.vue
  src/views/private-view/header-bar-actions/index.ts
  src/views/private-view/header-bar-actions/readme.md
  src/views/private-view/header-bar/header-bar.story.ts
  src/views/private-view/header-bar/header-bar.test.ts
  src/views/private-view/header-bar/header-bar.vue
  src/views/private-view/header-bar/index.ts
  src/views/private-view/header-bar/readme.md
  src/views/private-view/index.ts
  src/views/private-view/module-bar-logo/index.ts
  src/views/private-view/module-bar-logo/module-bar-logo.story.ts
  src/views/private-view/module-bar-logo/module-bar-logo.test.ts
  src/views/private-view/module-bar-logo/module-bar-logo.vue
  src/views/private-view/module-bar-logo/readme.md
  src/views/private-view/module-bar/index.ts
  src/views/private-view/module-bar/module-bar.story.ts
  src/views/private-view/module-bar/module-bar.vue
  src/views/private-view/module-bar/readme.md
  src/views/private-view/private-view.story.ts
  src/views/private-view/private-view.test.ts
  src/views/private-view/private-view.vue
  src/views/private-view/readme.md
  src/views/private/drawer-detail/drawer-detail.story.ts
  src/views/private/private-view.test.ts
  src/views/register.ts
Labels: views

#144 Add fields store
  src/auth.test.ts
  src/auth.ts
  src/hydrate.test.ts
  src/hydrate.ts
  src/router.test.ts
  src/stores/app/app.ts
  src/stores/app/index.ts
  src/stores/collections/collections.test.ts
  src/stores/collections/collections.ts
  src/stores/fields/fields.test.ts
  src/stores/fields/fields.ts
  src/stores/fields/index.ts
  src/stores/fields/types.ts
  src/stores/projects/projects.test.ts
  src/stores/requests/requests.ts
  src/views/private-view/module-bar-logo/module-bar-logo.test.ts
  src/views/private-view/module-bar-logo/module-bar-logo.vue
  src/views/public/public-view.test.ts
Labels: stores

#155 Interfaces registration
  src/components/v-input/v-input.readme.md
  src/interfaces/define.ts
  src/interfaces/index.ts
  src/interfaces/readme.md
  src/interfaces/register.ts
  src/interfaces/text-input/index.ts
  src/interfaces/text-input/readme.md
  src/interfaces/text-input/text-input.story.ts
  src/interfaces/text-input/text-input.test.ts
  src/interfaces/text-input/text-input.vue
  src/interfaces/text-input/types.ts
  src/interfaces/types.ts
  src/main.ts
  src/router.test.ts
  src/stores/collections/collections.test.ts
  src/stores/collections/collections.ts
Labels: interfaces

#156 Rename createX -> defineX + minor bug fixes
  src/components/v-progress/linear/v-progress-linear.vue
  src/components/v-table/types.ts
  src/layouts/define.ts
  src/layouts/tabular/index.ts
  src/modules/collections/index.ts
  src/modules/define.ts
  src/views/private-view/private-view.vue
Labels: bug, optimization

#163 Adds sonar to app
  .github/workflows/test.yml
  jest.config.js
  package.json
  sonar-project.properties
  yarn.lock
Labels: enhancement

#158 Collections module
  src/layouts/tabular/tabular.vue
  src/modules/collections/components/navigation/index.ts
  src/modules/collections/components/navigation/navigation.test.ts
  src/modules/collections/components/navigation/navigation.vue
  src/modules/collections/index.ts
  src/modules/collections/routes/browse/browse.test.ts
  src/modules/collections/routes/browse/browse.vue
  src/modules/collections/routes/browse/index.ts
  src/modules/collections/routes/detail/detail.test.ts
  src/modules/collections/routes/detail/detail.vue
  src/modules/collections/routes/detail/index.ts
  src/modules/collections/routes/overview/index.ts
  src/modules/collections/routes/overview/overview.test.ts
  src/modules/collections/routes/overview/overview.vue
Labels: layouts, modules

#164 Improve v-focus
  src/directives/focus/focus.readme.md
  src/directives/focus/focus.story.ts
  src/directives/focus/focus.test.ts
  src/directives/focus/focus.ts
  src/interfaces/text-input/text-input.story.ts
  src/routes/login/login.vue
Labels: directive

#166 Sonar fixes
  sonar-project.properties
  src/components/v-table/_table-header.vue
  src/components/v-table/v-table.vue
  src/compositions/readme.md
  src/compositions/use-event-listener.test.ts
  src/compositions/use-event-listener.ts
  src/compositions/use-time-from-now.test.ts
  src/compositions/use-time-from-now.ts
  src/compositions/use-window-size.test.ts
  src/compositions/use-window-size.ts
  src/lang/index.ts
  src/main.ts
  src/modules/register.ts
  src/views/private-view/module-bar-logo/module-bar-logo.vue
  src/views/private-view/private-view.vue
  src/views/public/_logo.vue
Labels: bug

#168 Document and structure utils / compositions
  sonar-project.properties
  src/components/v-item-group/v-item-group.test.ts
  src/components/v-item-group/v-item.test.ts
  src/compositions/groupable/groupable.test.ts
  src/compositions/groupable/groupable.ts
  src/compositions/groupable/index.ts
  src/compositions/groupable/readme.md
  src/compositions/readme.md
  src/compositions/size-class/index.ts
  src/compositions/size-class/readme.md
  src/compositions/size-class/size-class.test.ts
  src/compositions/size-class/size-class.ts
  src/compositions/use-event-listener/index.ts
  src/compositions/use-event-listener/readme.md
  src/compositions/use-event-listener/use-event-listener.test.ts
  src/compositions/use-event-listener/use-event-listener.ts
  src/compositions/use-time-from-now/readme.md
  src/compositions/use-time-from-now/use-time-from-now.test.ts
  src/compositions/use-time-from-now/use-time-from-now.ts
  src/compositions/use-window-size/readme.md
  src/compositions/use-window-size/use-window-size.test.ts
  src/compositions/use-window-size/use-window-size.ts
  src/interfaces/register.ts
  src/layouts/register.ts
  src/stores/collections/collections.ts
  src/stores/fields/fields.ts
  src/styles/readme.md
  src/utils/arrays-are-equal/arrays-are-equal.test.ts
  src/utils/arrays-are-equal/arrays-are-equal.ts
  src/utils/arrays-are-equal/index.ts
  src/utils/arrays-are-equal/readme.md
  src/utils/is-empty/index.ts
  src/utils/is-empty/is-empty.test.ts
  src/utils/is-empty/is-empty.ts
  src/utils/is-empty/readme.md
  src/utils/readme.md
  src/utils/register-component/index.ts
  src/utils/register-component/readme.md
  src/utils/register-component/register-component.test.ts
  src/utils/register-component/register-component.ts
  src/views/private-view/drawer-detail/drawer-detail.test.ts
  src/views/readme.md
Labels: optimization

#169 Use element size
  package.json
  src/compositions/use-element-size/index.ts
  src/compositions/use-element-size/readme.md
  src/compositions/use-element-size/use-element-size.test.ts
  src/compositions/use-element-size/use-element-size.ts
  yarn.lock
Labels: composition

#170 v-form
  src/components/register.ts
  src/components/v-form/index.ts
  src/components/v-form/readme.md
  src/components/v-form/v-form.story.ts
  src/components/v-form/v-form.test.ts
  src/components/v-form/v-form.vue
  src/modules/collections/routes/detail/detail.vue
  src/stores/fields/types.ts
  src/views/private-view/private-view.vue
Labels: base component

#171 Rename readme's to work with github
  src/components/v-avatar/readme.md
  src/components/v-avatar/v-avatar.story.ts
  src/components/v-badge/readme.md
  src/components/v-badge/v-badge.story.ts
  src/components/v-breadcrumb/readme.md
  src/components/v-breadcrumb/v-breadcrumb.story.ts
  src/components/v-button/readme.md
  src/components/v-button/v-button.story.ts
  src/components/v-checkbox/readme.md
  src/components/v-checkbox/v-checkbox.story.ts
  src/components/v-chip/readme.md
  src/components/v-chip/v-chip.story.ts
  src/components/v-hover/readme.md
  src/components/v-hover/v-hover.story.ts
  src/components/v-icon/readme.md
  src/components/v-icon/v-icon.story.ts
  src/components/v-input/readme.md
  src/components/v-input/v-input.story.ts
  src/components/v-item-group/readme.md
  src/components/v-item-group/v-item-group.story.ts
  src/components/v-list/readme.md
  src/components/v-list/v-list.story.ts
  src/components/v-notice/readme.md
  src/components/v-notice/v-notice.story.ts
  src/components/v-overlay/readme.md
  src/components/v-overlay/v-overlay.story.ts
  src/components/v-progress/circular/readme.md
  src/components/v-progress/circular/v-progress-circular.story.ts
  src/components/v-progress/linear/readme.md
  src/components/v-progress/linear/v-progress-linear.story.ts
  src/components/v-sheet/readme.md
  src/components/v-sheet/v-sheet.story.ts
  src/components/v-slider/readme.md
  src/components/v-slider/v-slider.story.ts
  src/components/v-switch/readme.md
  src/components/v-switch/v-switch.story.ts
  src/components/v-table/readme.md
  src/components/v-table/v-table.story.ts
  src/directives/focus/focus.story.ts
  src/directives/focus/readme.md
  src/directives/tooltip/readme.md
  src/directives/tooltip/tooltip.story.ts
  src/views/public/public-view.story.ts
  src/views/public/readme.md
Labels: optimization

#175 Add v-dialog component
  src/components/v-dialog/index.ts
  src/components/v-dialog/readme.md
  src/components/v-dialog/v-dialog.story.ts
  src/components/v-dialog/v-dialog.test.ts
  src/components/v-dialog/v-dialog.vue
  src/components/v-input/readme.md
Labels: base component

#173 List group
  src/components/register.ts
  src/components/transition/expand/index.ts
  src/components/transition/expand/readme.md
  src/components/transition/expand/transition-expand-methods.ts
  src/components/transition/expand/transition-expand.story.ts
  src/components/transition/expand/transition-expand.test.ts
  src/components/transition/expand/transition-expand.vue
  src/components/transition/index.ts
  src/components/transition/readme.md
  src/components/v-form/v-form.test.ts
  src/components/v-item-group/v-item-group.story.ts
  src/components/v-list/index.ts
  src/components/v-list/readme.md
  src/components/v-list/v-list-group.vue
  src/components/v-list/v-list-item-icon.vue
  src/components/v-list/v-list-item.vue
  src/components/v-list/v-list.story.ts
  src/components/v-list/v-list.test.ts
  src/components/v-list/v-list.vue
  src/modules/collections/components/navigation/navigation.test.ts
  src/utils/capitalize-first/capitalize-first.test.ts
  src/utils/capitalize-first/capitalize-first.ts
  src/utils/capitalize-first/index.ts
  src/views/private-view/drawer-detail/drawer-detail.vue
Labels: base component

#115 [WIP] Card component
  src/components/v-card/index.ts
  src/components/v-card/readme.md
  src/components/v-card/v-card-actions.vue
  src/components/v-card/v-card-subtitle.vue
  src/components/v-card/v-card-text.vue
  src/components/v-card/v-card-title.vue
  src/components/v-card/v-card.story.ts
  src/components/v-card/v-card.test.ts
  src/components/v-card/v-card.vue
  src/components/v-dialog/v-dialog.vue
  src/styles/mixins/type-styles.scss
  src/views/private-view/drawer-detail/drawer-detail.test.ts
Labels: base component

#202 Restructure views
  src/components/register.ts
  src/modules/collections/routes/browse/browse.test.ts
  src/modules/collections/routes/detail/detail.test.ts
  src/modules/collections/routes/overview/overview.test.ts
  src/views/private/components/drawer-detail-group/drawer-detail-group.story.ts
  src/views/private/components/drawer-detail-group/drawer-detail-group.test.ts
  src/views/private/components/drawer-detail-group/drawer-detail-group.vue
  src/views/private/components/drawer-detail-group/index.ts
  src/views/private/components/drawer-detail-group/readme.md
  src/views/private/components/drawer-detail/drawer-detail.story.ts
  src/views/private/components/drawer-detail/drawer-detail.test.ts
  src/views/private/components/drawer-detail/drawer-detail.vue
  src/views/private/components/drawer-detail/index.ts
  src/views/private/components/drawer-detail/readme.md
  src/views/private/components/header-bar-actions/header-bar-actions.story.ts
  src/views/private/components/header-bar-actions/header-bar-actions.test.ts
  src/views/private/components/header-bar-actions/header-bar-actions.vue
  src/views/private/components/header-bar-actions/index.ts
  src/views/private/components/header-bar-actions/readme.md
  src/views/private/components/header-bar/header-bar.story.ts
  src/views/private/components/header-bar/header-bar.test.ts
  src/views/private/components/header-bar/header-bar.vue
  src/views/private/components/header-bar/index.ts
  src/views/private/components/header-bar/readme.md
  src/views/private/components/module-bar-logo/index.ts
  src/views/private/components/module-bar-logo/module-bar-logo.story.ts
  src/views/private/components/module-bar-logo/module-bar-logo.test.ts
  src/views/private/components/module-bar-logo/module-bar-logo.vue
  src/views/private/components/module-bar-logo/readme.md
  src/views/private/components/module-bar-logo/sprite.svg
  src/views/private/components/module-bar/index.ts
  src/views/private/components/module-bar/module-bar.story.ts
  src/views/private/components/module-bar/module-bar.vue
  src/views/private/components/module-bar/readme.md
  src/views/private/index.ts
  src/views/private/private-view.story.ts
  src/views/private/private-view.test.ts
  src/views/private/private-view.vue
  src/views/private/readme.md
  src/views/public/components/logo/index.ts
  src/views/public/components/logo/logo-dark.svg
  src/views/public/components/logo/logo.story.ts
  src/views/public/components/logo/logo.vue
  src/views/public/components/logo/readme.md
  src/views/public/public-view.vue
  src/views/register.ts
Labels: optimization

#203 Add userStore, continue-as notification, bit of styling
  src/hydrate.ts
  src/router.test.ts
  src/router.ts
  src/routes/login/components/continue-as/continue-as.vue
  src/routes/login/components/continue-as/index.ts
  src/routes/login/components/login-form/index.ts
  src/routes/login/components/login-form/login-form.vue
  src/routes/login/login.vue
  src/stores/user/index.ts
  src/stores/user/types.ts
  src/stores/user/user.test.ts
  src/stores/user/user.ts
Labels: public

#206 Project switching
  src/app.vue
  src/auth.ts
  src/components/register.ts
  src/components/v-button/v-button.test.ts
  src/components/v-button/v-button.vue
  src/main.ts
  src/modules/collections/compositions/use-navigation.test.ts
  src/modules/collections/compositions/use-navigation.ts
  src/modules/collections/routes/browse/browse.vue
  src/modules/collections/routes/detail/detail.vue
  src/modules/collections/routes/overview/overview.vue
  src/router.ts
  src/routes/login/components/login-form/login-form.vue
  src/routes/login/components/project-error/index.ts
  src/routes/login/components/project-error/project-error.vue
  src/routes/login/login.vue
  src/routes/project-chooser/project-chooser.vue
  src/stores/projects/projects.test.ts
  src/stores/projects/projects.ts
  src/views/private/components/project-chooser/index.ts
  src/views/private/components/project-chooser/project-chooser.vue
  src/views/private/private-view.test.ts
  src/views/private/private-view.vue
Labels: routes, stores

#208 Add pagination component
  src/components/register.ts
  src/components/v-button/v-button.vue
  src/components/v-pagination/index.ts
  src/components/v-pagination/readme.md
  src/components/v-pagination/v-pagination.story.ts
  src/components/v-pagination/v-pagination.test.ts
  src/components/v-pagination/v-pagination.vue
Labels: base component

#209 Add show-first-last prop to pagination
  src/components/v-pagination/readme.md
  src/components/v-pagination/v-pagination.story.ts
  src/components/v-pagination/v-pagination.vue
Labels: base component

#201 Collections module additions
  src/api.test.ts
  src/components/register.ts
  src/components/v-button/v-button.vue
  src/components/v-card/index.ts
  src/components/v-card/v-card-title.vue
  src/components/v-dialog/readme.md
  src/components/v-dialog/v-dialog.vue
  src/components/v-form/v-form.vue
  src/components/v-table/readme.md
  src/components/v-table/table-header/index.ts
  src/components/v-table/table-header/readme.md
  src/components/v-table/table-header/table-header.test.ts
  src/components/v-table/table-header/table-header.vue
  src/components/v-table/table-row/index.ts
  src/components/v-table/table-row/readme.md
  src/components/v-table/table-row/table-row.test.ts
  src/components/v-table/table-row/table-row.vue
  src/components/v-table/v-table.story.ts
  src/components/v-table/v-table.test.ts
  src/components/v-table/v-table.vue
  src/compositions/use-element-size/use-element-size.ts
  src/compositions/use-scroll-distance/index.ts
  src/compositions/use-scroll-distance/readme.md
  src/compositions/use-scroll-distance/use-scroll-distance.story.ts
  src/compositions/use-scroll-distance/use-scroll-distance.test.ts
  src/compositions/use-scroll-distance/use-scroll-distance.ts
  src/layouts/tabular/tabular.vue
  src/layouts/types.ts
  src/modules/collections/compositions/use-navigation.ts
  src/modules/collections/index.ts
  src/modules/collections/routes/browse/browse.test.ts
  src/modules/collections/routes/browse/browse.vue
  src/modules/collections/routes/detail/detail.test.ts
  src/modules/collections/routes/detail/detail.vue
  src/modules/collections/routes/overview/overview.test.ts
  src/modules/collections/routes/overview/overview.vue
  src/stores/collections/collections.ts
  src/stores/fields/fields.ts
  src/styles/_variables.scss
  src/views/private/components/drawer-button/drawer-button.story.ts
  src/views/private/components/drawer-button/drawer-button.test.ts
  src/views/private/components/drawer-button/drawer-button.vue
  src/views/private/components/drawer-button/index.ts
  src/views/private/components/drawer-button/readme.md
  src/views/private/components/drawer-detail/drawer-detail.vue
  src/views/private/components/header-bar-actions/header-bar-actions.vue
  src/views/private/components/header-bar/header-bar.test.ts
  src/views/private/components/header-bar/header-bar.vue
  src/views/private/private-view.vue
  src/views/public/public-view.test.ts
  src/views/public/public-view.vue
Labels: modules

#224 Optimize data fetching on layout view
  src/layouts/tabular/tabular.vue
Labels: layouts

#225 Add portals
  package.json
  src/layouts/tabular/tabular.vue
  src/plugins.ts
  src/views/private/components/header-bar/header-bar.vue
  src/views/private/private-view.vue
  yarn.lock
Labels: dependency

#226 Add collection presets store
  src/hydrate.ts
  src/stores/app/app.ts
  src/stores/collection-presets/collection-presets.test.ts
  src/stores/collection-presets/collection-presets.ts
  src/stores/collection-presets/index.ts
  src/stores/collection-presets/types.ts
  src/stores/collections/collections.ts
  src/stores/fields/fields.ts
  src/stores/projects/projects.ts
  src/stores/requests/requests.ts
  src/stores/user/user.ts
Labels: stores

#232 Disable type checking in storybook
  .storybook/main.js
  tsconfig.json
Labels: optimization

#234 User sign out
  src/stores/user/types.ts
  src/stores/user/user.ts
  src/views/private/components/module-bar-avatar/index.ts
  src/views/private/components/module-bar-avatar/module-bar-avatar.story.ts
  src/views/private/components/module-bar-avatar/module-bar-avatar.test.ts
  src/views/private/components/module-bar-avatar/module-bar-avatar.vue
  src/views/private/components/module-bar-avatar/readme.md
  src/views/private/components/module-bar/module-bar.story.ts
  src/views/private/components/module-bar/module-bar.vue
  src/views/private/private-view.story.ts
Labels: enhancement

#238 Logout route
  src/app.vue
  src/modules/collections/components/navigation/navigation.test.ts
  src/router.test.ts
  src/router.ts
  src/routes/logout/index.ts
  src/routes/logout/logout.test.ts
  src/routes/logout/logout.vue
  src/routes/logout/readme.md
  src/stores/user/user.test.ts
  src/views/private/components/header-bar/header-bar.test.ts
  src/views/private/private-view.test.ts
Labels: routes

#240 Notifications
  src/app.vue
  src/stores/notifications/index.ts
  src/stores/notifications/notifications.test.ts
  src/stores/notifications/notifications.ts
  src/stores/notifications/types.ts
  src/utils/notify/index.ts
  src/utils/notify/notify.test.ts
  src/utils/notify/notify.ts
  src/views/private/components/notification-item/index.ts
  src/views/private/components/notification-item/notification-item.story.ts
  src/views/private/components/notification-item/notification-item.test.ts
  src/views/private/components/notification-item/notification-item.vue
  src/views/private/components/notification-item/readme.md
  src/views/private/components/notifications-group/index.ts
  src/views/private/components/notifications-group/notifications-group.story.ts
  src/views/private/components/notifications-group/notifications-group.vue
  src/views/private/components/notifications-group/readme.md
  src/views/private/private-view.vue
Labels: enhancement, utils, views

#246 Save layout options query
  src/components/v-table/readme.md
  src/components/v-table/table-header/table-header.vue
  src/components/v-table/v-table.vue
  src/compositions/readme.md
  src/compositions/use-sync/index.ts
  src/compositions/use-sync/readme.md
  src/compositions/use-sync/use-sync.ts
  src/lang/en-US/index.json
  src/lang/en-US/layouts.json
  src/layouts/tabular/tabular.vue
  src/modules/collections/routes/browse/browse.vue
  src/stores/collection-presets/collection-presets.test.ts
  src/stores/collection-presets/collection-presets.ts
  src/stores/collection-presets/default-collection-preset.ts
  src/stores/collection-presets/types.ts
  src/views/private/components/header-bar/header-bar.vue
  src/views/private/private-view.vue
Labels: layouts, stores

#247 Stacking context
  src/app.vue
  src/components/v-dialog/v-dialog.story.ts
  src/components/v-dialog/v-dialog.test.ts
  src/components/v-dialog/v-dialog.vue
Labels: bug

#249 Add support for Displays
  .storybook/preview.js
  src/displays/define.ts
  src/displays/format-title/format-title.story.ts
  src/displays/format-title/format-title.test.ts
  src/displays/format-title/handler.ts
  src/displays/format-title/index.ts
  src/displays/format-title/readme.md
  src/displays/icon/icon.story.ts
  src/displays/icon/icon.test.ts
  src/displays/icon/icon.vue
  src/displays/icon/index.ts
  src/displays/icon/readme.md
  src/displays/index.ts
  src/displays/readme.md
  src/displays/register.ts
  src/displays/types.ts
  src/interfaces/define.ts
  src/interfaces/readme.md
  src/interfaces/register.ts
  src/interfaces/text-input/index.ts
  src/interfaces/types.ts
  src/layouts/define.ts
  src/layouts/tabular/index.ts
  src/layouts/types.ts
  src/main.ts
  src/modules/collections/index.ts
  src/modules/collections/routes/browse/browse.vue
  src/modules/define.ts
  src/modules/types.ts
Labels: displays

#218 Menu
  jest.config.js
  package.json
  src/components/v-input/v-input.story.ts
  src/components/v-input/v-input.vue
  src/components/v-list/readme.md
  src/components/v-list/v-list.vue
  src/components/v-menu/index.ts
  src/components/v-menu/readme.md
  src/components/v-menu/use-popper.ts
  src/components/v-menu/v-menu.story.ts
  src/components/v-menu/v-menu.test.ts
  src/components/v-menu/v-menu.vue
  src/compositions/use-window-size/index.ts
  src/directives/click-outside/click-outside.story.ts
  src/directives/click-outside/click-outside.test.ts
  src/directives/click-outside/click-outside.ts
  src/directives/click-outside/index.ts
  src/directives/click-outside/readme.md
  src/directives/register.ts
  src/styles/themes/_default.scss
  yarn.lock
Labels: base component

#252 Add divider component
  src/components/v-divider/index.ts
  src/components/v-divider/readme.md
  src/components/v-divider/v-divider.story.ts
  src/components/v-divider/v-divider.test.ts
  src/components/v-divider/v-divider.vue
Labels: base component

#258 Start on data model settings
  src/app.vue
  src/components/register.ts
  src/components/v-divider/readme.md
  src/components/v-divider/v-divider.story.ts
  src/components/v-divider/v-divider.vue
  src/components/v-icon/v-icon.vue
  src/components/v-input/v-input.vue
  src/components/v-list/readme.md
  src/components/v-list/v-list-item.vue
  src/components/v-menu/use-popper.ts
  src/components/v-menu/v-menu.vue
  src/compositions/use-collection/index.ts
  src/compositions/use-collection/use-collection.test.ts
  src/compositions/use-collection/use-collection.ts
  src/displays/types.ts
  src/lang/en-US/index.json
  src/modules/define.ts
  src/modules/index.ts
  src/modules/settings/components/navigation/index.ts
  src/modules/settings/components/navigation/navigation.vue
  src/modules/settings/index.ts
  src/modules/settings/routes/data-model/collections/collections.vue
  src/modules/settings/routes/data-model/collections/components/new-collection/index.ts
  src/modules/settings/routes/data-model/collections/components/new-collection/new-collection.vue
  src/modules/settings/routes/data-model/collections/index.ts
  src/modules/settings/routes/data-model/fields/components/field-select/field-select.vue
  src/modules/settings/routes/data-model/fields/components/field-select/index.ts
  src/modules/settings/routes/data-model/fields/components/field-setup/field-setup.vue
  src/modules/settings/routes/data-model/fields/components/field-setup/index.ts
  src/modules/settings/routes/data-model/fields/components/fields-management/fields-management.vue
  src/modules/settings/routes/data-model/fields/components/fields-management/index.ts
  src/modules/settings/routes/data-model/fields/fields.vue
  src/modules/settings/routes/data-model/fields/index.ts
  src/modules/settings/routes/data-model/index.ts
  src/modules/settings/routes/global/global.vue
  src/modules/settings/routes/global/index.ts
  src/modules/settings/routes/roles/global/global.vue
  src/modules/settings/routes/roles/global/index.ts
  src/modules/settings/routes/roles/index.ts
  src/modules/settings/routes/roles/roles.vue
  src/modules/settings/routes/webhooks/index.ts
  src/modules/settings/routes/webhooks/webhooks.vue
  src/routes/logout/logout.test.ts
  src/stores/fields/fields.ts
  src/stores/notifications/types.ts
  src/utils/move-in-array/index.ts
  src/utils/move-in-array/move-in-array.ts
  src/views/private/components/project-chooser/project-chooser.vue
Labels: base component, directive, enhancement, modules, optimization

#262 Add v-select component
  .storybook/raw-value.vue
  src/components/v-menu/use-popper.ts
  src/components/v-menu/v-menu.vue
  src/components/v-select/index.ts
  src/components/v-select/readme.md
  src/components/v-select/v-select.story.ts
  src/components/v-select/v-select.test.ts
  src/components/v-select/v-select.vue
Labels: base component

#263 [Settings] Add duplicate field option
  src/components/register.ts
  src/components/v-dialog/v-dialog.vue
  src/components/v-menu/use-popper.ts
  src/components/v-menu/v-menu.vue
  src/components/v-select/readme.md
  src/components/v-select/v-select.vue
  src/lang/en-US/index.json
  src/modules/settings/routes/data-model/fields/components/field-select/field-select.vue
  src/modules/settings/routes/data-model/fields/components/fields-management/fields-management.vue
  src/stores/fields/fields.ts
Labels: modules

#274 Add v-modal component
  src/components/register.ts
  src/components/v-card/v-card.vue
  src/components/v-dialog/v-dialog.vue
  src/components/v-list/readme.md
  src/components/v-list/v-list-item.vue
  src/components/v-modal/index.ts
  src/components/v-modal/readme.md
  src/components/v-modal/v-modal.story.ts
  src/components/v-modal/v-modal.test.ts
  src/components/v-modal/v-modal.vue
  src/components/v-tabs/v-tab/v-tab.vue
  src/components/v-tabs/v-tabs.vue
  src/compositions/groupable/groupable.ts
  src/compositions/groupable/readme.md
Labels: base component

#275 Update v-form to accept fields prop
  src/components/v-form/readme.md
  src/components/v-form/types.ts
  src/components/v-form/v-form.story.ts
  src/components/v-form/v-form.vue
  src/interfaces/text-input/text-input.vue
  src/interfaces/text-input/types.ts
  src/stores/fields/types.ts
Labels: base component
