Repository directus/app-next, pull requests merged in 2020-02, with the labels that each got.

#28 Use size class
  src/components/v-avatar/v-avatar.test.ts
  src/components/v-avatar/v-avatar.vue
  src/components/v-button/v-button.test.ts
  src/components/v-button/v-button.vue
  src/components/v-chip/v-chip.test.ts
  src/components/v-chip/v-chip.vue
  src/components/v-icon/v-icon.test.ts
  src/components/v-icon/v-icon.vue
  src/components/v-spinner/v-spinner.test.ts
  src/components/v-spinner/v-spinner.vue
  src/compositions/readme.md
  src/compositions/size-class.test.ts
  src/compositions/size-class.ts
Labels: composition

#35 Added click feedback
  src/components/v-button/v-button.test.ts
  src/components/v-button/v-button.vue
Labels: base component

#39 Add base public view
  src/components/v-sheet/v-sheet.test.ts
  src/components/v-sheet/v-sheet.vue
  src/routes/debug.vue
  src/styles/lib/_tooltip.scss
  src/views/public/public-view.readme.md
  src/views/public/public-view.test.ts
  src/views/public/public-view.vue
  src/views/public/types.ts
Labels: views

#41 Private view
  package.json
  src/api.test.ts
  src/api.ts
  src/components/register.ts
  src/components/v-hover/v-hover.test.ts
  src/main.ts
  src/routes/debug.vue
  src/stores/projects.test.ts
  src/stores/requests.test.ts
  src/stores/requests.ts
  src/styles/mixins/breakpoint.scss
  src/views/private/_module-bar-logo.test.ts
  src/views/private/_module-bar-logo.vue
  src/views/private/_module-bar.vue
  src/views/private/index.ts
  src/views/private/private-view.readme.md
  src/views/private/private-view.story.ts
  src/views/private/private-view.test.ts
  src/views/private/private-view.vue
  src/views/public/public-view.test.ts
  yarn.lock
Labels: views

#42 Add breadcrumb component
  src/components/v-breadcrumb/index.ts
  src/components/v-breadcrumb/v-breadcrumb.readme.md
  src/components/v-breadcrumb/v-breadcrumb.story.ts
  src/components/v-breadcrumb/v-breadcrumb.test.ts
  src/components/v-breadcrumb/v-breadcrumb.vue
  src/components/v-icon/v-icon.vue
Labels: base component

#111 Add to prop support on v-button
  src/components/v-button/v-button.readme.md
  src/components/v-button/v-button.story.ts
  src/components/v-button/v-button.test.ts
  src/components/v-button/v-button.vue
Labels: base component

#112 Modules store and bar
  src/components/v-button/v-button.readme.md
  src/components/v-button/v-button.vue
  src/main.ts
  src/modules/collections/index.ts
  src/modules/files/index.ts
  src/modules/index.ts
  src/modules/register.test.ts
  src/modules/register.ts
  src/modules/settings/index.ts
  src/modules/types.ts
  src/modules/users/index.ts
  src/router.ts
  src/stores/modules/index.ts
  src/stores/modules/modules.test.ts
  src/stores/modules/modules.ts
  src/stores/projects/index.ts
  src/stores/projects/projects.test.ts
  src/stores/projects/projects.ts
  src/stores/projects/types.ts
  src/stores/requests/index.ts
  src/stores/requests/requests.test.ts
  src/stores/requests/requests.ts
  src/styles/_colors.scss
  src/styles/themes/_default.scss
  src/types/modules.ts
  src/types/readme.md
  src/views/private/_module-bar-logo.vue
  src/views/private/_module-bar.vue
  src/views/private/private-view.vue
  src/views/public/public-view.test.ts
  src/views/public/public-view.vue
Labels: views

#114 Create auth helpers file, check auth on failed requests, change beforeRoute handler
  package.json
  src/api.test.ts
  src/api.ts
  src/auth.test.ts
  src/auth.ts
  src/components/v-button/v-button.test.ts
  src/lang/index.ts
  src/router.test.ts
  src/router.ts
  src/routes/debug.vue
  src/routes/project-chooser/index.ts
  src/routes/project-chooser/project-chooser.vue
  src/stores/projects/projects.test.ts
  src/stores/projects/projects.ts
  src/stores/requests/requests.ts
  src/views/private/private-view.vue
Labels: optimization

#116 Implement router dynamic route replacement logic
  src/directives/tooltip/tooltip.test.ts
  src/directives/tooltip/tooltip.ts
  src/main.ts
  src/modules/collections/collections.vue
  src/modules/files/files.vue
  src/modules/index.ts
  src/modules/register.test.ts
  src/modules/register.ts
  src/modules/settings/settings.vue
  src/modules/users/users.vue
  src/router.test.ts
  src/router.ts
  src/stores/modules/modules.test.ts
  src/stores/modules/modules.ts
  src/views/private/private-view.vue
Labels: enhancement, optimization

#120 Add layout registration logic
  package.json
  src/layouts/register.test.ts
  src/layouts/register.ts
  src/layouts/tabular/index.ts
  src/layouts/tabular/tabular.vue
  src/main.ts
  src/modules/collections/index.ts
  src/modules/files/index.ts
  src/modules/register.test.ts
  src/modules/register.ts
  src/modules/settings/index.ts
  src/modules/users/index.ts
  src/stores/extensions/extensions.ts
  src/stores/extensions/index.ts
  src/stores/modules/index.ts
  src/stores/modules/modules.ts
  src/types/extensions.ts
  src/utils/register-component.test.ts
  src/utils/register-component.ts
  src/views/private/_module-bar.vue
Labels: layout

#122 Test config
  jest.config.js
  src/api.test.ts
  src/auth.test.ts
  src/components/v-item-group/v-item-group.vue
  src/directives/tooltip/tooltip.test.ts
  src/router.test.ts
  src/views/private/private-view.test.ts
Labels: optimization, tests

#123 Private View / Drawer Detail
  src/components/register.ts
  src/components/v-list/v-list-item.vue
  src/components/v-list/v-list.readme.md
  src/components/v-list/v-list.vue
  src/styles/themes/_default.scss
  src/types/icon.ts
  src/views/private/_drawer-detail-group.test.ts
  src/views/private/_drawer-detail-group.vue
  src/views/private/drawer-detail/drawer-detail.readme.md
  src/views/private/drawer-detail/drawer-detail.story.ts
  src/views/private/drawer-detail/drawer-detail.test.ts
  src/views/private/drawer-detail/drawer-detail.vue
  src/views/private/drawer-detail/index.ts
  src/views/private/private-view.vue
Labels: base component, views

#124 Extension registration
  src/interfaces/readme.md
  src/layouts/create.ts
  src/layouts/index.ts
  src/layouts/readme.md
  src/layouts/register.test.ts
  src/layouts/register.ts
  src/layouts/tabular/index.ts
  src/layouts/tabular/tabular.vue
  src/layouts/types.ts
  src/main.ts
  src/modules/collections/index.ts
  src/modules/create.ts
  src/modules/files/files.vue
  src/modules/files/index.ts
  src/modules/index.ts
  src/modules/readme.md
  src/modules/register.test.ts
  src/modules/register.ts
  src/modules/settings/index.ts
  src/modules/settings/settings.vue
  src/modules/types.ts
  src/modules/users/index.ts
  src/modules/users/users.vue
  src/stores/extensions/extensions.ts
  src/stores/extensions/index.ts
  src/stores/projects/types.ts
  src/types/extensions.ts
  src/types/icon.ts
  src/types/project.ts
  src/types/readme.md
  src/views/private/_module-bar.vue
  src/views/private/drawer-detail/drawer-detail.story.ts
  src/views/private/drawer-detail/drawer-detail.vue
  src/views/private/private-view.story.ts
Labels: optimization

#125 Add hydration, collection store, collections module navigation
  package.json
  src/api.test.ts
  src/api.ts
  src/auth.test.ts
  src/auth.ts
  src/components/v-list/v-list.readme.md
  src/components/v-list/v-list.story.ts
  src/hydrate.test.ts
  src/hydrate.ts
  src/main.ts
  src/modules/collections/collections.vue
  src/modules/collections/components/collections-navigation.test.ts
  src/modules/collections/components/collections-navigation.vue
  src/modules/collections/compositions/use-navigation.test.ts
  src/modules/collections/compositions/use-navigation.ts
  src/modules/collections/index.ts
  src/modules/collections/routes/collections-overview.test.ts
  src/modules/collections/routes/collections-overview.vue
  src/router.test.ts
  src/router.ts
  src/routes/login/login.vue
  src/stores/collections/collections.ts
  src/stores/collections/index.ts
  src/stores/collections/types.ts
  src/stores/projects/projects.ts
  src/views/private/private-view.vue
  yarn.lock
Labels: enhancement, module, stores

#126 Start alt-colors overrides
  src/styles/themes/_default.scss
  src/views/private/private-view.vue
Labels: enhancement

#127 Fix tooltips
  src/directives/tooltip/tooltip.ts
Labels: bug
